OBS-DevOps24/whoknows-legacy

legacycode/src/backend/app.py
legacycode/src/backend/app_tests.py

Updated the legacy code according to https://github.com/who-knows-inc/whoknows_variations/commit/369fee84c6ca5c2f4f77e75952bd8228810bddce

 Changed the route from /logout to /api/logout

---

.github/workflows/backend-test-build.yml
.github/workflows/frontend-build.yml

Added workflows for building and testing backend and frontend
Closes #14

GitHub workflow

---

README.MD

Adding badges

---

docs/branching-strategy.md
docs/framework-choice.md

Docs changes + addition of branching strategy

---

.github/issue_template/bug_report.md
.github/issue_template/feature_request.md
.github/issue_template/generic.md

Issue template

---

.github/issue_template/config.yml

config.yml for issue template

---

backend/API/Controllers/AuthController.cs
backend/API/Controllers/SearchController.cs
docs/openapi.yaml

Changed API routes to match specs that we were given.

OpenAPI specs

---

.github/workflows/deploy.yml
.gitignore
backend/API/.env.sample
backend/API/Dockerfile
backend/API/Models/Page.cs
backend/API/Program.cs
db/.dockerignore
db/Dockerfile
db/schema.sql
frontend/.dockerignore
frontend/Dockerfile
frontend/nginx/nginx.conf
nginx/Dockerfile
nginx/nginx.conf

Dockerized application and added a workflow to automatically deploy to production (for now triggered manually).
Fixes #40 

40 dockerize and setup gh workflow for image push

---

backend/API/Controllers/SearchController.cs
backend/API/Interfaces/IPageRepository.cs
backend/API/Interfaces/IPageService.cs
backend/API/Program.cs
backend/API/Repositories/PageRepository.cs
backend/API/Services/PageService.cs

Added search route according to specifications
Fixes #34 

34 api get apisearch

---

backend/API.Tests/API.Tests.csproj
backend/API.Tests/AuthControllerTest.cs
backend/API/API.csproj
backend/API/Controllers/AuthController.cs
backend/API/Interfaces/IAuthService.cs
backend/API/Models/Dtos/RegisterDTO.cs
backend/API/Program.cs
backend/API/Services/AuthService.cs
backend/backend.sln

Added service, dto, interface etc. - uses BCrypt on register to hash passwords.
Fixes #11 

/api/register logic added

---

nginx/nginx.conf

Added extra logging to the nginx conf file
Fixes #52 

Added extra logging

---

backend/API/Program.cs
frontend/Settings.ts

Cors settings should now allow all localhost entries

reverted settings.tsx + changed cors settings

---

frontend/Settings.ts

wrong production api :)

---

backend/API.Tests/Controllers/AuthControllerTest.cs
backend/API/Models/Dtos/RegisterDTO.cs
backend/API/Services/AuthService.cs
frontend/src/pages/register/RegisterForm.tsx

Made password2 optional. Service still compares passwords, if you include both

Password2 optional

---

backend/API/Models/Dtos/RegisterDTO.cs

Updated password2 with '?'

---

docs/openapi.yaml

Openapi docs

---

README.MD
backend/API.Tests/Controllers/AuthControllerTest.cs
backend/API/Controllers/AuthController.cs
backend/API/Controllers/SearchController.cs
backend/API/Controllers/WeatherController.cs
backend/API/Program.cs

Added sonarcloud with small code smell fixes
Fixes #67

67 feature add software quality check

---

.github/workflows/deploy.yml

Pushes docker images to specific version, and latest. And added zero downtime for deploying containers
Fixes #74 

74 feature use git tag release for docker images

---

.github/workflows/deploy.yml

Pushes docker images to specific version, and latest. And added zero downtime for deploying containers
Note: FIXING TAG RELEASE EXTRACTION
Fixes #74 

Fix extract release tag

---

.github/workflows/deploy.yml

fixed deploy.yml env var

---

docker-compose.yml

Update to docker compose file

---

.github/workflows/deploy.yml

Updated `deploy.yml`  script:
- SCP env vars to servers
- SCP docker-compose file to server
Helps keeping a single source of truth

Gh actions deploy

---

backend/API.Tests/Controllers/AuthControllerTest.cs
backend/API/Controllers/AuthController.cs
backend/API/Interfaces/IAuthService.cs
backend/API/Program.cs
backend/API/Services/AuthService.cs
frontend/src/pages/register/RegisterForm.tsx
frontend/src/services/apiFacade.ts
nginx/nginx.conf

Login is now automatic after registration. Also fixed sonarcloud false positive issue, and testing new nginx conf to hopefully fix 415 error from simulation.
Fixes #84 

Login on registration

---

.github/dependabot.yml

specify package eco-system and directory

specify package eco-system and directory

---

backend/API/Middleware/TokenBlacklistMiddleware.cs
backend/API/Program.cs

Fixed token blacklisting for authorized endpoints (not that we have any), by reintroducing the blacklist custom middleware.

Token blacklist fixed

---

backend/API/Models/Dtos/RegisterDTO.cs
backend/API/Services/AuthService.cs
frontend/src/pages/register/RegisterForm.tsx

fixed bug where mail couldn't contain æ,ø,å
Fixes #124 

fixed bug where mail couldn't contain æ,ø,å

---

frontend/src/Footer.tsx
frontend/src/Header.tsx
frontend/src/Layout.tsx
frontend/src/pages/about/About.tsx

Added link to weather page and about page + made footer component.
Fixes #130 

Fix footer, about page and weather page

---

backend/API/API.csproj
backend/API/Program.cs
backend/backend.sln

Added open telemetry for more data for prometheus

Monitoring

---

.github/workflows/deploy-monitoring.yml
monitoring/docker-compose.yml
monitoring/prometheus/prometheus.yml

Added monitoring of VM1 with node exporter

added monitoring of VM1 with node-exporter

---

frontend/eslint.config.js
frontend/postcss.config.js
frontend/src/App.tsx
frontend/src/Layout.tsx
frontend/src/context/AuthContext.tsx
frontend/src/interfaces/types.ts
frontend/src/pages/changePassword/ChangePassword.tsx
frontend/src/pages/changePassword/RequireAuth.tsx
frontend/src/pages/changePassword/RequirePasswordChange.tsx
frontend/src/pages/changePassword/SecurityBreachBanner.tsx
frontend/src/services/apiFacade.ts
frontend/tailwind.config.js

Fixing security breach, see [here](https://github.com/who-knows-inc/KEA_DAT_DevOps_2024_Autumn/blob/main/00._Course_Material/01._Assignments/09._Testing_Security/02._After/security_breach.md).
The user is forced to change password, because of the security breach.
Fixes #143

Security breach frontend

---

.github/workflows/deploy-monitoring.yml
monitoring/docker-compose.yml

Changed retention days of prometheus metrics + updated deploy yaml

Prometheus retention days

---

monitoring/docker-compose.yml

typo in retention tag

---

frontend/end2end/login.spec.ts

fix e2e test with firefox :)))

---

monitoring/prometheus/prometheus.yml.template

added node_exporter to vm2

---

.github/workflows/deploy-monitoring.yml

- Added VM_IP_2 to monitoring workflow

updated monitoring workflow to include vm_ip_2
